# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk

# Set the working directory in the container
WORKDIR /app


# Copy the executable JAR file from the host to the container
COPY target/taskManager-0.0.1-SNAPSHOT.jar app.jar


# Expose the port that your application runs on
EXPOSE 8080

# Command to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]

